### ISSUE TITLE
Build fails :(

### ISSUE THREAD

**Issue by ColinGilbert** [wichtounet/articles#6] opened 2015-02-09 06:20 UTC
Hi, great articles!

Unfortunately, the overall build using

```
git clone --recursive https://github.com/wichtounet/articles.git
cd articles
make
```

Gives this error on my system:

```
clang++ -Iinclude -std=c++1y -Wextra -Wall -Qunused-arguments -Wuninitialized -Wsometimes-uninitialized -Wno-long-long -Winit-self -Wdocumentation -DSQRT_VALUE=5000000 -ICatch/include -g -DNDEBUG -O3 -fvectorize -fslp-vectorize-aggressive -fomit-frame-pointer -march=native  -o release/src/threads/part1/Hello0.cpp.o -c src/threads/part1/Hello0.cpp
In file included from src/threads/part1/Hello0.cpp:8:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/thread:39:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/functional:55:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/tuple:39:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/array:38:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/stdexcept:39:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/string:52:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/bits/basic_string.h:2815:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/ext/string_conversions.h:43:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
Makefile:17: recipe for target 'release/src/threads/part1/Hello0.cpp.o' failed
make: *** [release/src/threads/part1/Hello0.cpp.o] Error 1
```

**Comment by wichtounet** [comment] 2015-02-14 10:17
Hi, 

The problem is that you need either: a) a more recent version of g++ or b) libc++

if you have libc++, you can add these lines. 

ifneq (,$(findstring clang,$(CXX)))
	CXX_FLAGS += -stdlib=libc++
endif

in the Makefile after the include lines and it should use libc++ instead of libstdc++

**Comment by wichtounet** [comment] 2016-11-09 12:38
I'm closing this issue, please reopen if this is still a problem.

**Closed by wichtounet** 2016-11-09 12:38 UTC
